### ISSUE TITLE
installing package crashes my app

### ISSUE THREAD

**Issue by mostafa17dev** [jankapunkt/meteor-autoform-bpmn#1]
I tried installing the package into newly created meteor app 'meteor create bpmn'
then 'meteor' inside the directory and the app runs smoothly
then 
'meteor add jkuester:autoform-bpmn'
then 
'meteor npm install --save simpl-schema bpmn-js diagram-js matches-selector font-awesome'
then i got all these errors through console

Uncaught SyntaxError: Unexpected identifier
babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:17
    at babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:149
(anonymous) @ babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:17
(anonymous) @ babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:149
promise.js?hash=9ba5b4e2acdf19ad7b7bac54d00338de4c1ecd0d:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at promise.js?hash=9ba5b4e2acdf19ad7b7bac54d00338de4c1ecd0d:17
    at promise.js?hash=9ba5b4e2acdf19ad7b7bac54d00338de4c1ecd0d:747
(anonymous) @ promise.js?hash=9ba5b4e2acdf19ad7b7bac54d00338de4c1ecd0d:17
(anonymous) @ promise.js?hash=9ba5b4e2acdf19ad7b7bac54d00338de4c1ecd0d:747
url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:17
    at url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:117
(anonymous) @ url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:17
(anonymous) @ url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:117
http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:17 Uncaught TypeError: Cannot read property 'URL' of undefined
    at http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:17
    at http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:363
(anonymous) @ http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:17
(anonymous) @ http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:363
dynamic-import.js?hash=1c93fd1a1f413455236b82d65c5740b88f2c9a82:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at dynamic-import.js?hash=1c93fd1a1f413455236b82d65c5740b88f2c9a82:17
    at dynamic-import.js?hash=1c93fd1a1f413455236b82d65c5740b88f2c9a82:517
(anonymous) @ dynamic-import.js?hash=1c93fd1a1f413455236b82d65c5740b88f2c9a82:17
(anonymous) @ dynamic-import.js?hash=1c93fd1a1f413455236b82d65c5740b88f2c9a82:517
ecmascript-runtime-client.js?hash=4f06b5aec4eb39ffb7ce8091fb57f9995646422b:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at ecmascript-runtime-client.js?hash=4f06b5aec4eb39ffb7ce8091fb57f9995646422b:17
    at ecmascript-runtime-client.js?hash=4f06b5aec4eb39ffb7ce8091fb57f9995646422b:115
(anonymous) @ ecmascript-runtime-client.js?hash=4f06b5aec4eb39ffb7ce8091fb57f9995646422b:17
(anonymous) @ ecmascript-runtime-client.js?hash=4f06b5aec4eb39ffb7ce8091fb57f9995646422b:115
base64.js?hash=70034bf297d812d5eea319d7eab8841e8009be3d:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at base64.js?hash=70034bf297d812d5eea319d7eab8841e8009be3d:17
    at base64.js?hash=70034bf297d812d5eea319d7eab8841e8009be3d:225
(anonymous) @ base64.js?hash=70034bf297d812d5eea319d7eab8841e8009be3d:17
(anonymous) @ base64.js?hash=70034bf297d812d5eea319d7eab8841e8009be3d:225
ejson.js?hash=7587586380ce943e916a569cb87a4487a2c97889:17 Uncaught TypeError: Cannot read property 'Base64' of undefined
    at ejson.js?hash=7587586380ce943e916a569cb87a4487a2c97889:17
    at ejson.js?hash=7587586380ce943e916a569cb87a4487a2c97889:883
(anonymous) @ ejson.js?hash=7587586380ce943e916a569cb87a4487a2c97889:17
(anonymous) @ ejson.js?hash=7587586380ce943e916a569cb87a4487a2c97889:883
diff-sequence.js?hash=9744098811e6a7f11abf1872a0689a21e3766407:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at diff-sequence.js?hash=9744098811e6a7f11abf1872a0689a21e3766407:17
    at diff-sequence.js?hash=9744098811e6a7f11abf1872a0689a21e3766407:307
(anonymous) @ diff-sequence.js?hash=9744098811e6a7f11abf1872a0689a21e3766407:17
(anonymous) @ diff-sequence.js?hash=9744098811e6a7f11abf1872a0689a21e3766407:307
geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:17
    at geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:438
(anonymous) @ geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:17
(anonymous) @ geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:438
id-map.js?hash=73c7b30c5c3b42f275ffa8e279c9ab7d526e38da:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at id-map.js?hash=73c7b30c5c3b42f275ffa8e279c9ab7d526e38da:17
    at id-map.js:83
(anonymous) @ id-map.js?hash=73c7b30c5c3b42f275ffa8e279c9ab7d526e38da:17
(anonymous) @ id-map.js:83
random.js?hash=3a0a1fb2f692cc600789180c65e0614eb4d1945a:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at random.js?hash=3a0a1fb2f692cc600789180c65e0614eb4d1945a:17
    at random.js?hash=3a0a1fb2f692cc600789180c65e0614eb4d1945a:346
(anonymous) @ random.js?hash=3a0a1fb2f692cc600789180c65e0614eb4d1945a:17
(anonymous) @ random.js?hash=3a0a1fb2f692cc600789180c65e0614eb4d1945a:346
mongo-id.js?hash=2f2a83467fca25b9f42f5bfaef5abe29526393e5:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at mongo-id.js?hash=2f2a83467fca25b9f42f5bfaef5abe29526393e5:17
    at mongo-id.js?hash=2f2a83467fca25b9f42f5bfaef5abe29526393e5:212
(anonymous) @ mongo-id.js?hash=2f2a83467fca25b9f42f5bfaef5abe29526393e5:17
(anonymous) @ mongo-id.js?hash=2f2a83467fca25b9f42f5bfaef5abe29526393e5:212
ordered-dict.js?hash=6effe900e78276f8fb4fcdfcd45c649cb21fe50e:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at ordered-dict.js?hash=6effe900e78276f8fb4fcdfcd45c649cb21fe50e:17
    at ordered-dict.js?hash=6effe900e78276f8fb4fcdfcd45c649cb21fe50e:384
(anonymous) @ ordered-dict.js?hash=6effe900e78276f8fb4fcdfcd45c649cb21fe50e:17
(anonymous) @ ordered-dict.js?hash=6effe900e78276f8fb4fcdfcd45c649cb21fe50e:384
minimongo.js?hash=18352629137a3b94ee43f8994aec3f9d4fd225d7:17 Uncaught TypeError: Cannot read property 'DiffSequence' of undefined
    at minimongo.js?hash=18352629137a3b94ee43f8994aec3f9d4fd225d7:17
    at minimongo.js?hash=18352629137a3b94ee43f8994aec3f9d4fd225d7:5129
(anonymous) @ minimongo.js?hash=18352629137a3b94ee43f8994aec3f9d4fd225d7:17
(anonymous) @ minimongo.js?hash=18352629137a3b94ee43f8994aec3f9d4fd225d7:5129
check.js?hash=7d8a6e550ea7ab9936e21a2d9bb76f12882fb043:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at check.js?hash=7d8a6e550ea7ab9936e21a2d9bb76f12882fb043:17
    at check.js?hash=7d8a6e550ea7ab9936e21a2d9bb76f12882fb043:678
(anonymous) @ check.js?hash=7d8a6e550ea7ab9936e21a2d9bb76f12882fb043:17
(anonymous) @ check.js?hash=7d8a6e550ea7ab9936e21a2d9bb76f12882fb043:678
retry.js?hash=b7e99dfd5eebf2adeecff68d150fc22e0d86f855:17 Uncaught TypeError: Cannot read property 'Random' of undefined
    at retry.js?hash=b7e99dfd5eebf2adeecff68d150fc22e0d86f855:17
    at retry.js:65
(anonymous) @ retry.js?hash=b7e99dfd5eebf2adeecff68d150fc22e0d86f855:17
(anonymous) @ retry.js:65
callback-hook.js?hash=8bdf3b5506fd2197bffa0db605fa422b9022fd10:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at callback-hook.js?hash=8bdf3b5506fd2197bffa0db605fa422b9022fd10:17
    at callback-hook.js?hash=8bdf3b5506fd2197bffa0db605fa422b9022fd10:212
(anonymous) @ callback-hook.js?hash=8bdf3b5506fd2197bffa0db605fa422b9022fd10:17
(anonymous) @ callback-hook.js?hash=8bdf3b5506fd2197bffa0db605fa422b9022fd10:212
ddp-common.js?hash=eba4c7e6cb7e9e642d2a8baafe6a87a01d8ed9f0:17 Uncaught TypeError: Cannot read property 'check' of undefined
    at ddp-common.js?hash=eba4c7e6cb7e9e642d2a8baafe6a87a01d8ed9f0:17
    at ddp-common.js?hash=eba4c7e6cb7e9e642d2a8baafe6a87a01d8ed9f0:606
(anonymous) @ ddp-common.js?hash=eba4c7e6cb7e9e642d2a8baafe6a87a01d8ed9f0:17
(anonymous) @ ddp-common.js?hash=eba4c7e6cb7e9e642d2a8baafe6a87a01d8ed9f0:606
reload.js?hash=96a42973e40fe6ee6372056266fe93b211f8b4f9:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at reload.js?hash=96a42973e40fe6ee6372056266fe93b211f8b4f9:17
    at reload.js?hash=96a42973e40fe6ee6372056266fe93b211f8b4f9:264
(anonymous) @ reload.js?hash=96a42973e40fe6ee6372056266fe93b211f8b4f9:17
(anonymous) @ reload.js?hash=96a42973e40fe6ee6372056266fe93b211f8b4f9:264
socket-stream-client.js?hash=f8b39dfba9fdeafe7c1ee49d011814e2bb921087:17 Uncaught TypeError: Cannot read property 'Retry' of undefined
    at socket-stream-client.js?hash=f8b39dfba9fdeafe7c1ee49d011814e2bb921087:17
    at socket-stream-client.js?hash=f8b39dfba9fdeafe7c1ee49d011814e2bb921087:3376
(anonymous) @ socket-stream-client.js?hash=f8b39dfba9fdeafe7c1ee49d011814e2bb921087:17
(anonymous) @ socket-stream-client.js?hash=f8b39dfba9fdeafe7c1ee49d011814e2bb921087:3376
ddp-client.js?hash=53be61ea50e289ef291ca3b87b6968a50594ce80:17 Uncaught TypeError: Cannot read property 'check' of undefined
    at ddp-client.js?hash=53be61ea50e289ef291ca3b87b6968a50594ce80:17
    at ddp-client.js?hash=53be61ea50e289ef291ca3b87b6968a50594ce80:2389
(anonymous) @ ddp-client.js?hash=53be61ea50e289ef291ca3b87b6968a50594ce80:17
(anonymous) @ ddp-client.js?hash=53be61ea50e289ef291ca3b87b6968a50594ce80:2389
ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:14 Uncaught TypeError: Cannot read property 'DDP' of undefined
    at ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:14
    at ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:23
(anonymous) @ ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:14
(anonymous) @ ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:23
allow-deny.js?hash=17efd8167bebe1f2018f9c642d8000a549d1fe26:17 Uncaught TypeError: Cannot read property 'LocalCollection' of undefined
    at allow-deny.js?hash=17efd8167bebe1f2018f9c642d8000a549d1fe26:17
    at allow-deny.js?hash=17efd8167bebe1f2018f9c642d8000a549d1fe26:566
(anonymous) @ allow-deny.js?hash=17efd8167bebe1f2018f9c642d8000a549d1fe26:17
(anonymous) @ allow-deny.js?hash=17efd8167bebe1f2018f9c642d8000a549d1fe26:566
mongo.js?hash=7dae0d2bbf4992c92bbb005435b6ee27a23d13b2:17 Uncaught TypeError: Cannot read property 'AllowDeny' of undefined
    at mongo.js?hash=7dae0d2bbf4992c92bbb005435b6ee27a23d13b2:17
    at mongo.js?hash=7dae0d2bbf4992c92bbb005435b6ee27a23d13b2:871
(anonymous) @ mongo.js?hash=7dae0d2bbf4992c92bbb005435b6ee27a23d13b2:17
(anonymous) @ mongo.js?hash=7dae0d2bbf4992c92bbb005435b6ee27a23d13b2:871
webapp.js?hash=d9bcd3b76f81f229f6f340c1b450a20471787855:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at webapp.js?hash=d9bcd3b76f81f229f6f340c1b450a20471787855:17
    at webapp.js?hash=d9bcd3b76f81f229f6f340c1b450a20471787855:73
(anonymous) @ webapp.js?hash=d9bcd3b76f81f229f6f340c1b450a20471787855:17
(anonymous) @ webapp.js?hash=d9bcd3b76f81f229f6f340c1b450a20471787855:73
server-render.js?hash=65b41eb13dc3c997744242f8c4b2daf4d19ca5cd:17 Uncaught TypeError: Cannot read property 'WebApp' of undefined
    at server-render.js?hash=65b41eb13dc3c997744242f8c4b2daf4d19ca5cd:17
    at server-render.js?hash=65b41eb13dc3c997744242f8c4b2daf4d19ca5cd:203
(anonymous) @ server-render.js?hash=65b41eb13dc3c997744242f8c4b2daf4d19ca5cd:17
(anonymous) @ server-render.js?hash=65b41eb13dc3c997744242f8c4b2daf4d19ca5cd:203
es5-shim.js?hash=b47b88652a29a06a9b65c6003b9d5cff9507473f:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at es5-shim.js?hash=b47b88652a29a06a9b65c6003b9d5cff9507473f:17
    at es5-shim.js?hash=b47b88652a29a06a9b65c6003b9d5cff9507473f:68
(anonymous) @ es5-shim.js?hash=b47b88652a29a06a9b65c6003b9d5cff9507473f:17
(anonymous) @ es5-shim.js?hash=b47b88652a29a06a9b65c6003b9d5cff9507473f:68
jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:17
    at jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:11100
(anonymous) @ jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:17
(anonymous) @ jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:11100
observe-sequence.js?hash=5da2e60ce61e074a6463979f3992dd5bac41b43d:19 Uncaught TypeError: Cannot read property 'MongoID' of undefined
    at observe-sequence.js?hash=5da2e60ce61e074a6463979f3992dd5bac41b43d:19
    at observe-sequence.js?hash=5da2e60ce61e074a6463979f3992dd5bac41b43d:403
(anonymous) @ observe-sequence.js?hash=5da2e60ce61e074a6463979f3992dd5bac41b43d:19
(anonymous) @ observe-sequence.js?hash=5da2e60ce61e074a6463979f3992dd5bac41b43d:403
blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:17 Uncaught TypeError: Cannot read property '$' of undefined
    at blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:17
    at blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3894
(anonymous) @ blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:17
(anonymous) @ blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3894
spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:17 Uncaught TypeError: Cannot read property 'ObserveSequence' of undefined
    at spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:17
    at spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:331
(anonymous) @ spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:17
(anonymous) @ spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:331
templating-runtime.js?hash=0d383d6c0c2772772a6e7c4451eca7cb8f6a7559:18 Uncaught TypeError: Cannot read property 'Blaze' of undefined
    at templating-runtime.js?hash=0d383d6c0c2772772a6e7c4451eca7cb8f6a7559:18
    at templating-runtime.js?hash=0d383d6c0c2772772a6e7c4451eca7cb8f6a7559:252
(anonymous) @ templating-runtime.js?hash=0d383d6c0c2772772a6e7c4451eca7cb8f6a7559:18
(anonymous) @ templating-runtime.js?hash=0d383d6c0c2772772a6e7c4451eca7cb8f6a7559:252
templating.js?hash=f2c84fce6d8b04d2702ff547986293031866f706:14 Uncaught TypeError: Cannot read property 'Template' of undefined
    at templating.js?hash=f2c84fce6d8b04d2702ff547986293031866f706:14
    at templating.js?hash=f2c84fce6d8b04d2702ff547986293031866f706:23
(anonymous) @ templating.js?hash=f2c84fce6d8b04d2702ff547986293031866f706:14
(anonymous) @ templating.js?hash=f2c84fce6d8b04d2702ff547986293031866f706:23
livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:14 Uncaught TypeError: Cannot read property 'DDP' of undefined
    at livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:14
    at livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:27
(anonymous) @ livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:14
(anonymous) @ livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:27
ui.js?hash=73201242e628677db1e85e5024826e6b9b4ede91:14 Uncaught TypeError: Cannot read property 'Blaze' of undefined
    at ui.js?hash=73201242e628677db1e85e5024826e6b9b4ede91:14
    at ui.js?hash=73201242e628677db1e85e5024826e6b9b4ede91:27
(anonymous) @ ui.js?hash=73201242e628677db1e85e5024826e6b9b4ede91:14
(anonymous) @ ui.js?hash=73201242e628677db1e85e5024826e6b9b4ede91:27
reactive-dict.js?hash=e1f032cd2a48186f99b331b4f3017f1c1dbea988:20 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at reactive-dict.js?hash=e1f032cd2a48186f99b331b4f3017f1c1dbea988:20
    at reactive-dict.js:245
(anonymous) @ reactive-dict.js?hash=e1f032cd2a48186f99b331b4f3017f1c1dbea988:20
(anonymous) @ reactive-dict.js:245
aldeed_autoform.js?hash=b4f1e8a35f46e0800a1ad99d4b5d1a1156ebd5ba:17 Uncaught TypeError: Cannot read property 'DDP' of undefined
    at aldeed_autoform.js?hash=b4f1e8a35f46e0800a1ad99d4b5d1a1156ebd5ba:17
    at aldeed_autoform.js?hash=b4f1e8a35f46e0800a1ad99d4b5d1a1156ebd5ba:10690
(anonymous) @ aldeed_autoform.js?hash=b4f1e8a35f46e0800a1ad99d4b5d1a1156ebd5ba:17
(anonymous) @ aldeed_autoform.js?hash=b4f1e8a35f46e0800a1ad99d4b5d1a1156ebd5ba:10690
aldeed_template-extension.js?hash=4a165da949d7df27f1b12d5f1c325bbadced5fd2:17 Uncaught TypeError: Cannot read property 'Template' of undefined
    at aldeed_template-extension.js?hash=4a165da949d7df27f1b12d5f1c325bbadced5fd2:17
    at aldeed_template-extension.js?hash=4a165da949d7df27f1b12d5f1c325bbadced5fd2:623
(anonymous) @ aldeed_template-extension.js?hash=4a165da949d7df27f1b12d5f1c325bbadced5fd2:17
(anonymous) @ aldeed_template-extension.js?hash=4a165da949d7df27f1b12d5f1c325bbadced5fd2:623
tmeasday_check-npm-versions.js?hash=95fa42758264e61292a0ac664409277ab5a9f02a:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at tmeasday_check-npm-versions.js?hash=95fa42758264e61292a0ac664409277ab5a9f02a:17
    at tmeasday_check-npm-versions.js?hash=95fa42758264e61292a0ac664409277ab5a9f02a:1328
(anonymous) @ tmeasday_check-npm-versions.js?hash=95fa42758264e61292a0ac664409277ab5a9f02a:17
(anonymous) @ tmeasday_check-npm-versions.js?hash=95fa42758264e61292a0ac664409277ab5a9f02a:1328
jkuester_autoform-bpmn.js?hash=bf48527625dda9d801b4c9809670008c883e24d0:17 Uncaught TypeError: Cannot read property 'Template' of undefined
    at jkuester_autoform-bpmn.js?hash=bf48527625dda9d801b4c9809670008c883e24d0:17
    at jkuester_autoform-bpmn.js?hash=bf48527625dda9d801b4c9809670008c883e24d0:633
(anonymous) @ jkuester_autoform-bpmn.js?hash=bf48527625dda9d801b4c9809670008c883e24d0:17
(anonymous) @ jkuester_autoform-bpmn.js?hash=bf48527625dda9d801b4c9809670008c883e24d0:633
autoupdate.js?hash=46bd3f2f0da4ac91a35983d5b3f812777ff52758:19 Uncaught TypeError: Cannot read property 'Retry' of undefined
    at autoupdate.js?hash=46bd3f2f0da4ac91a35983d5b3f812777ff52758:19
    at autoupdate.js?hash=46bd3f2f0da4ac91a35983d5b3f812777ff52758:231
(anonymous) @ autoupdate.js?hash=46bd3f2f0da4ac91a35983d5b3f812777ff52758:19
(anonymous) @ autoupdate.js?hash=46bd3f2f0da4ac91a35983d5b3f812777ff52758:231
global-imports.js?hash=e00fccbcbee1aabaa1c38cc2f9e8470535546ab4:3 Uncaught TypeError: Cannot read property 'Mongo' of undefined
    at global-imports.js?hash=e00fccbcbee1aabaa1c38cc2f9e8470535546ab4:3
(anonymous) @ global-imports.js?hash=e00fccbcbee1aabaa1c38cc2f9e8470535546ab4:3
app.js?hash=017b24555d53257cf7b36845efbd815388013537:1 Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=017b24555d53257cf7b36845efbd815388013537:1
(anonymous) @ app.js?hash=017b24555d53257cf7b36845efbd815388013537:1

and when i remove the package 'meteor remove jkuester:autoform-bpmn'  the errors are gone.
Could you please help me.

**Comment by jankapunkt** [comment]
hi @mostafa17dev can you please add the Meteor Version and the Operating System you are running on to your issue?  So I can reproduce your error as good as possible.

**Comment by jankapunkt** [comment]
I found the issue and publish a new version within the next hours. There will also be some updated documentation as there are breaking changes.

**Comment by jankapunkt** [comment]
Package is updated to version 0.1.1 - I missed to publish 0.1.0 to atmosphere. Please also read the updated readme, as you are now not required anymore to install the bpmn dependencies manually.

Please confirm or deny that it's working now.

**Comment by jankapunkt** [comment]
You are welcome! I will close the issue. Feel free to reopen if there are still any problems related to this issue or open a new one if you face any other error.
